### PR TITLE
Skip unit tests in windows

### LINKED ISSUE #82: fix unit test failures on Windows
**What happened**:

following unit test could not pass on Windows, we should either fix those failures on Windows or disable those tests running on Windows
```
C:\Users\xiazhang\go\src\github.com\kubernetes-csi\csi-driver-smb\pkg\smb>go test
E0812 10:32:35.859486 1580532 nodeserver.go:313] MakeDir failed on target: ./smb.go (mkdir ./smb.go: The system cannot find the path specified.)
--- FAIL: TestNodeStageVolume (0.04s)
    nodeserver_test.go:122: test case: [Error] Not a Directory, Unexpected error: rpc error: code = Internal desc = Could not mount target "./smb.go": mkdir ./smb.go: The system cannot find the path specified.
    nodeserver_test.go:122: test case: [Error] Failed SMB mount mocked by MountSensitive, Unexpected error: prepare stage path failed for ./error_mount_sens_source with error: could not cast to csi proxy class
    nodeserver_test.go:122: test case: [Success] Valid request, Unexpected error: prepare stage path failed for ./source_test with error: could not cast to csi proxy class
E0812 10:32:35.915490 1580532 nodeserver.go:313] MakeDir failed on target: ./smb.go (mkdir ./smb.go: The system cannot find the path specified.)
--- FAIL: TestNodePublishVolume (0.02s)
    nodeserver_test.go:274: test case: [Error] Not a directory, Unexpected error: rpc error: code = Internal desc = Could not mount target "./smb.go": mkdir ./smb.go: The system cannot find the path specified.
    nodeserver_test.go:274: test case: [Error] Mount error mocked by Mount, Unexpected error: prepare publish failed for ./target_test with error: could not cast to csi proxy class
    nodeserver_test.go:274: test case: [Success] Valid request read only, Unexpected error: prepare publish failed for ./target_test with error: could not cast to csi proxy class
    nodeserver_test.go:274: test case: [Success] Valid request, Unexpected error: prepare publish failed for ./target_test with error: could not cast to csi proxy class
--- FAIL: TestNodeUnpublishVolume (0.00s)
    nodeserver_test.go:327: test case: [Error] Unmount error mocked by IsLikelyNotMountPoint, Unexpected error: rpc error: code = Internal desc = failed to unmount target "./error_is_likely_target": could not cast to csi proxy class
    nodeserver_test.go:327: test case: [Success] Valid request, Unexpected error: rpc error: code = Internal desc = failed to unmount target "./abc.go": could not cast to csi proxy class
--- FAIL: TestNodeUnstageVolume (0.00s)
    nodeserver_test.go:378: test case: [Error] CleanupMountPoint error mocked by IsLikelyNotMountPoint, Unexpected error: rpc error: code = Internal desc = failed to unmount staging target "./error_is_likely_target": could not cast to csi proxy class
    nodeserver_test.go:378: test case: [Success] Valid request, Unexpected error: rpc error: code = Internal desc = failed to unmount staging target "./abc.go": could not cast to csi proxy class
IsCorruptedDir(./error_is_likely_target) returned with error: <nil>W0812 10:32:35.983487 1580532 nodeserver.go:303] ReadDir ./false_is_likely_target failed with open ./false_is_likely_target: The system cannot find the file specified., unmount this directory
E0812 10:32:35.984504 1580532 nodeserver.go:313] MakeDir failed on target: ./smb.go (mkdir ./smb.go: The system cannot find the path specified.)
--- FAIL: TestIsCorruptedDir (0.00s)
    smb_test.go:54: failed to create curruptedPath: symlink C:\Users\xiazhang\AppData\Local\Temp\csi-mount-test216866723 C:\Users\xiazhang\AppData\Local\Temp\csi-mount-test216866723\curruptedPath: A required privilege is not held by the client.
I0812 10:32:36.012492 1580532 smb.go:58]
DRIVER INFORMATION:
-------------------
Build Date: N/A
Compiler: gc
Driver Name: smb.csi.k8s.io
Driver Version: N/A
Git Commit: N/A
Go Version: go1.13.14
```
**What you expected to happen**:

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
- CSI Driver version:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by mayankshah1607**
Signed-off-by: Mayank Shah <mayankshah1614@gmail.com>

**What type of PR is this?**
/kind test
/kind flake

**What this PR does / why we need it**:

This PR skips the following tests in `pkg/smb` when running on Windows environment:

- `TestNodeStageVolume`
- `TestNodePublishVolume`
- `TestNodeUnpublishVolume`
- `TestNodeUnstageVolume`
- `TestIsCorruptedDir`

**Which issue(s) this PR fixes**:

Fixes #82

**Requirements**:
- [x] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [x] includes documentation
- [x] adds unit tests
- [x] tested upgrade from previous version

**Release note**:
```
none
```

### CODE REVIEW

**Comment by mayankshah1607** [comment]
CLA has been signed! :)

**Comment by andyzhangx** [comment]
```
Cannot find golangci-lint. Installing golangci-lint...
golangci/golangci-lint info checking GitHub for tag 'v1.30.0'
golangci/golangci-lint info found version: 1.30.0 for v1.30.0/linux/amd64
golangci/golangci-lint info installed /home/prow/go/bin/golangci-lint
pkg/smb/nodeserver_test.go:42:2: S1008: should use 'return runtime.GOOS == "windows"' instead of 'if runtime.GOOS == "windows" { return true }; return false' (gosimple)
	if runtime.GOOS == "windows" {
	^
make: *** [Makefile:50: verify] Error 1
+ EXIT_VALUE=2
+ set +o xtrace
```

File: pkg/smb/smb_test.go [hunk 1]
```diff
@@ -43,6 +43,10 @@ func TestNewFakeDriver(t *testing.T) {
 }
 
 func TestIsCorruptedDir(t *testing.T) {
+	if isWindows() {
```
Comment (andyzhangx) [inline pkg/smb/smb_test.go:46]: what about write like this:
```
skipIfTestingInWindows(t)
```

and in func `skipIfTestingInWindows`:
```
	if runtime == windows {
		t.Skip("Skipping tests on Windows")
	}
```

that could reduce code

Comment (mayankshah1607) [reply pkg/smb/smb_test.go:46]: Makes sense! On it :)

**Review by andyzhangx — APPROVED** [review]
/lgtm
/approve
