### PR TITLE
Fix username and password exposed in logs

### LINKED ISSUE #7: password should not be exposed in logs
**What happened**:
password should not be exposed in logs:
```
 nodeserver.go:120] NodeStageVolume called with request {arbitrary-volumeid map[] /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pv-smb/globalmount mount:<mount_flags:"dir_mode=0777" mount_flags:"file_mode=0777" mount_flags:"vers=3.0" > access_mode:<mode:MULTI_NODE_MULTI_WRITER >  map[password:..dYGisUKDE3axDL6x1KyEj9j9PrUp0Yd7U/WbZ0Ip1uluWQr8FSkFgQhIO6fhaCGKd+aJSCrnTgR3m99OMQ== username:f8471372a68594910913ed4] map[source://f8471372a68594910913ed4.file.core.windows.net/kubernetes-dynamic-pvc-687cfca7-4880-4dbc-9daa-be4bc39b8eaa] {} [] 0}
I0510 03:32:33.846897       1 nodeserver.go:169] targetPath(/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pv-smb/globalmount) volumeID(arbitrary-volumeid) context(map[source://xxx.file.core.windows.net/kubernetes-dynamic-pvc-687cfca7-4880-4dbc-9daa-be4bc39b8eaa]) mountflags([dir_mode=0777 file_mode=0777 vers=3.0]) mountOptions([dir_mode=0777 file_mode=0777 username=f8471372a68594910913ed4,password=...YGisUKDE3axDL6x1KyEj9j9PrUp0Yd7U/WbZ0Ip1uluWQr8FSkFgQhIO6fhaCGKd+aJSCrnTgR3m99OMQ== vers=3.0])
```

https://github.com/csi-driver/csi-driver-smb/blob/bcd8d774b631d8a6281ed7184a357183c84fff29/deploy/example/logs/csi-smb-node.log#L39

similar to fix: https://github.com/kubernetes-sigs/azurefile-csi-driver/pull/64

related code:
https://github.com/csi-driver/csi-driver-smb/blob/bcd8d774b631d8a6281ed7184a357183c84fff29/pkg/csi-common/utils.go#L112

**What you expected to happen**:

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
- CSI Driver version:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by animeshk08**
Signed-off-by: Animesh Kumar <animuz111@gmail.com>

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind test
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #7 

**Special notes for your reviewer**:
A new test file has been created. The current test is specific to this Fix.
I will try and add a complete test file in another PR.

**Release note**:
```
Fixes password which get exposed in logs.
```

### CODE REVIEW

File: pkg/smb/nodeserver.go [hunk 1]
```diff
@@ -117,7 +118,13 @@ func (d *Driver) NodeUnpublishVolume(ctx context.Context, req *csi.NodeUnpublish
 
 // NodeStageVolume mount the volume to a staging path
 func (d *Driver) NodeStageVolume(ctx context.Context, req *csi.NodeStageVolumeRequest) (*csi.NodeStageVolumeResponse, error) {
-	klog.V(2).Infof("NodeStageVolume called with request %v", *req)
+
+	// regex to mask username and password in log messages
+	var reqSecretsRegex, _ = regexp.Compile("map\\[password:.*? username:.*?\\]")
+
+	s := fmt.Sprintf("NodeStageVolume called with request %v", *req)
+	klog.V(5).Info(reqSecretsRegex.ReplaceAllString(s, "map[password:**** username:****]"))
```
Comment (andyzhangx) [inline pkg/smb/nodeserver.go:126]: let's expose the username in the logs

File: pkg/smb/nodeserver.go [hunk 2]
```diff
@@ -117,7 +118,13 @@ func (d *Driver) NodeUnpublishVolume(ctx context.Context, req *csi.NodeUnpublish
 
 // NodeStageVolume mount the volume to a staging path
 func (d *Driver) NodeStageVolume(ctx context.Context, req *csi.NodeStageVolumeRequest) (*csi.NodeStageVolumeResponse, error) {
-	klog.V(2).Infof("NodeStageVolume called with request %v", *req)
+
```
Comment (andyzhangx) [inline pkg/smb/nodeserver.go:121]: remove this empty line

File: pkg/smb/smb_test.go [hunk 3]
```diff
@@ -17,14 +17,30 @@ limitations under the License.
...
 	"testing"
+)
 
-	"github.com/stretchr/testify/assert"
+const (
+	fakeNodeID = "fakeNodeID"
 )
 
+func NewFakeDriver() *Driver {
+
```
Comment (andyzhangx) [inline pkg/smb/smb_test.go:32]: pls remove these empty lines next time, thanks.
